const CREATE_TASK = "CREATE_TASK";
const DELETE_TASK = "DELETE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";
const TASK_IN_EDIT = "TASK_IN_EDIT";

export { CREATE_TASK, DELETE_TASK, UPDATE_TASK, TOGGLE_EDIT_MODAL, TASK_IN_EDIT };